# Face embedding extractor parameters
face_extract:
  batch_size: 2048
  data_path: "/mnt/parscratch/users/acp21jrc/ego4d_data/self_lifting/imgs"                             # User fills this
  manifest_file: "/mnt/parscratch/users/acp21jrc/ego4d_data/sl_FVA_ASD/annot/image_manifest.csv"       # Path to CSV with audio/video metadata
  save_path: "/mnt/parscratch/users/acp21jrc/sl_FVA_ASD/dataset/Ego4D"                                 # Where to save embeddings
  n_dataloader_thread: 12
  model_settings:
    pretrained: "vggface2"
    classify: true