# Voice embedding extractor parameters
voice_extract:

  # types: groundtruth; pyannote_MD-0.0

  batch_size: 16
  data_path:   # Path to audio files
  manifest_file:    # CSV with 'fpath' column
  save_path:     # Embedding output directory
  model_path:  # Path to pretrained ECAPA-TDNN model
  n_dataloader_thread: 12